# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6817d95fd48ff626b6377a98466bee0bcc2814d0ef61146b8a1ea3b0ebfddc34b2eb47302e1756a427ffc479e5738adcf6e08ca6683e0bb98c79613bc8cc6334

test:
  secret_key_base: ba0569ac1f7f99a5031c63c6a2b938f875d39f2081cb355b7d7553601c48b09493a5ec607dd17a027f1dcca9136320b11a7647a647641873651bd65079184a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
